name: CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Running Release Please
        uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: master
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          monorepo-tags: true
          release-type: node
          pull-request-title-pattern: "chore${scope}: release${component} ${version}"

      # - name: Publish packages
      #  if: ${{ steps.release.outputs.releases_created }}
      #  run: pnpm -r publish --access public
